### ISSUE TITLE
Pledgevegan style guide

### ISSUE THREAD

**Issue by JordanDDisch** [rcaracaus/pledge-vegan-client#108]
- [x] place all components in style guide follow example.
- [ ] install node-kss styleguide
- [ ] add meta data to components so stylguide generates properly

**Comment by JordanDDisch** [comment]
[ ] - asdf

**Comment by milesthedisch** [comment]
Pledge Vegan Components

- [ ] body
- [ ] button
- [ ] clearfix
- [ ] element-invisible
- [ ] font
- [ ] header
- [ ] horizontal-list
- [ ] image-float
- [ ] inset
- [ ] layout-narrow
- [ ] listing
- [ ] palette 
- [ ] rounded-corners
- [ ] sign-up
- [ ] spacer
- [ ] text-decoration
- [ ] vertical-image-listing

**Comment by milesthedisch** [comment]
put html files into sass component folders


still need to put meta tags in html file

**Comment by milesthedisch** [comment]
- [] install style guide
- []
