### ISSUE TITLE
Enchance Design of <ul> and <ol> (1/2)

### ISSUE THREAD

**Issue by milesthedisch** [rcaracaus/pledge-vegan-client#146]

**Comment by JordanDDisch** [comment]
look at other examples.
no padding
bullets of to side of page

**Comment by milesthedisch** [comment]
![screen shot 2015-02-20 at 5 04 10 pm](https://cloud.githubusercontent.com/assets/6229386/6281263/7533a2ac-b922-11e4-80ea-57630490c93f.png)

like this

**Comment by milesthedisch** [comment]
how do we want these lists?

**Comment by JordanDDisch** [comment]
@milesthedisch see [here](http://www.pledgevegan.com/veganic-growing-stock-free-farming-future)
The bullets are outside the main paragraph

**Comment by milesthedisch** [comment]
wtf happened to the style guide?

**Comment by JordanDDisch** [comment]
@milesthedisch you have to do all the new styling in a separate repo called [pledge-vegan-style-guide](https://github.com/rcaracaus/pledge-vegan-styleguide).
Clone the repo and follow the [read me](https://github.com/rcaracaus/pledge-vegan-client/blob/master/README.md)

**Comment by milesthedisch** [comment]
read me is not clear to me cause pledge-vegan-styleguide is not in bower-components.

**Comment by JordanDDisch** [comment]
@milesthedisch you need to pull the latest version of master and do a bower install

**Comment by milesthedisch** [comment]
did that
![screen shot 2015-04-10 at 10 00 48 pm](https://cloud.githubusercontent.com/assets/6229386/7087293/1dbdecea-dfcd-11e4-85d4-23231090a20a.png)

**Comment by milesthedisch** [comment]
screen share?

**Comment by milesthedisch** [comment]
![screen shot 2015-04-10 at 10 04 42 pm](https://cloud.githubusercontent.com/assets/6229386/7087335/a19ed470-dfcd-11e4-9de5-442e2fa09857.png)
