### ISSUE TITLE
Add google event when product clicked

### ISSUE THREAD

**Issue by rcaracaus** [rcaracaus/pledge-vegan-client#178]

**Comment by JordanDDisch** [comment]
3 hrs
- May run into complications, I have never messed with google analytic code before.

**Comment by milesthedisch** [comment]
block quote is fine the <p> tags are fuqing the padding 
![screen shot 2015-02-12 at 12 55 14 am](https://cloud.githubusercontent.com/assets/6229386/6148049/04caa334-b252-11e4-9583-64afb7123e86.png)
