### ISSUE TITLE
Stronger call to action for sign-up page.

### ISSUE THREAD

**Issue by rcaracaus** [rcaracaus/pledge-vegan-client#232]
Currently the call to action link in the upper left hand side of the site is not obvious enough. We are not getting nearly as many sign-ups as we used to get. We should bring the call to action out of the header and strategically place on all devices.

You can make the pledge text in upper left in header fade bold when it appears.

We can add a sign up form on left side of featured image on node detail page. It doesn't need to appear on smaller screens. It can fade in when you scroll down.

**Comment by JordanDDisch** [comment]
- needs to be on the left of layout narrow on large screens
- small screens but back in top corner
