### ISSUE TITLE
listing item without image looks bad

### ISSUE THREAD

**Issue by JordanDDisch** [rcaracaus/pledge-vegan-client#73]
![screen shot 2014-12-30 at 8 24 45 pm](https://cloud.githubusercontent.com/assets/4076759/5577277/ed7ef714-9061-11e4-9184-e8eca4b09b09.png)
http://live-pledge-vegan.pantheon.io/ryan-gosslings-letter-national-milk-producers-federation-regarding-dehorning
http://www.pledgevegan.com/watch-discuss-award-winning-documentary-earthlings
http://www.pledgevegan.com/i-decided-go-vegan-now-what

**Comment by rcaracaus** [comment]
Wrap an if statement in handlebars .html template around image
